### ISSUE TITLE
installed the taichi==0.6.39 succefully, but when install taichi_glsl, got module 'ti' has no attribute 'static' or has no 'Matrix'

### ISSUE THREAD

**Issue by visonpon** [DSaurus/DeepMultiCap#2]
Hi, thanks for sharing this wonderful work , but I encounted above error when set up my own environment, hope you can help. thanks~

**Comment by DSaurus** [comment]
Can you provide more information? Is your version of taichi_glsl equal to 0.0.10? Or you can try to install taichi==0.7.15, which also runs our test successfully.

**Comment by visonpon** [comment]
after installed taichi, i can import it ,but when use taichi.Matrix or taichi.Vector, I got the no attribute error.

but I have modified the `packages = setuptoos.find_packages() + [taichi.examples] `to` packages = setuptoos.find_packages()` or `packages = setuptoos.find_packages(./taichi/examples)`,since in my environment the original script trigger the error 'taichi/examples' does not exist.

**Comment by DSaurus** [comment]
I think there may be some problems when you install taichi==0.6.39. You can try to uninstall it and install taichi==0.7.15 using pip directly.

**Comment by visonpon** [comment]
got it , thanks~
